In [3]:
try:
  %tensorflow_version 2.x
except Exception:
    pass

TensorFlow 2.x selected.


In [4]:
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.0.0


In [0]:
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()



In [8]:
x_train.shape

(60000, 28, 28)

In [9]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [10]:
len(y_train)

60000

In [11]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [12]:
x_test.shape

(10000, 28, 28)

In [13]:
len(y_test)

10000

In [0]:
x_train = x_train / 255.0

x_test = x_test / 255.0

In [0]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(100, activation='softsign'),
    keras.layers.Dense(130, activation='softplus'),
    keras.layers.Dense(10, activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [21]:
model.fit(x_train,y_train,epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 8s 130us/sample - loss: 0.2400 - accuracy: 0.9291
Epoch 2/10
60000/60000 [==============================] - 6s 108us/sample - loss: 0.0980 - accuracy: 0.9706
Epoch 3/10
60000/60000 [==============================] - 6s 108us/sample - loss: 0.0696 - accuracy: 0.9776
Epoch 4/10
60000/60000 [==============================] - 6s 107us/sample - loss: 0.0532 - accuracy: 0.9837
Epoch 5/10
60000/60000 [==============================] - 6s 106us/sample - loss: 0.0419 - accuracy: 0.9864
Epoch 6/10
60000/60000 [==============================] - 6s 107us/sample - loss: 0.0344 - accuracy: 0.9887
Epoch 7/10
60000/60000 [==============================] - 6s 105us/sample - loss: 0.0297 - accuracy: 0.9897
Epoch 8/10
60000/60000 [==============================] - 6s 106us/sample - loss: 0.0250 - accuracy: 0.9913
Epoch 9/10
60000/60000 [==============================] - 7s 109us/sample - loss: 0.0232 - accuracy: 0.9922
Epoch

In [23]:
test_loss, test_acc = model.evaluate(x_test,  y_test, verbose=2)

print('\nTest accuracy:', test_acc)

10000/1 - 1s - loss: 0.0398 - accuracy: 0.9805

Test accuracy: 0.9805


In [0]:
predictions=model.predict(x_test)

In [25]:
predictions[0]

array([1.8726792e-10, 2.0903634e-07, 9.4549691e-08, 5.9482960e-07,
       2.8409170e-08, 9.3979280e-10, 2.2645560e-13, 9.9998915e-01,
       1.0502065e-08, 9.8539622e-06], dtype=float32)

In [26]:
np.argmax(predictions[0])

7

In [27]:
y_test[0]

7